In [1]:
import pandas as pd
import numpy as np
import pyfpgrowth

df=pd.read_csv('df_Liquor.csv')

In [2]:
print(df.shape)
print(df.info())
display(df.head())

(1899, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1899 entries, 0 to 1898
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             1899 non-null   int64
 1   Receipt No.            1899 non-null   int64
 2   Date                   1899 non-null   int64
 3   Time                   1899 non-null   int64
 4   Customer ID            1899 non-null   int64
 5   Price before tax       1899 non-null   int64
 6   Unit price before tax  1899 non-null   int64
 7   Number                 1899 non-null   int64
 8   Category No.           1899 non-null   int64
 9   Category name          1899 non-null   object
 10  Subcategory No.        1899 non-null   int64
 11  Subcategory            1899 non-null   object
 12  Subsubcategory No.     1899 non-null   int64
 13  Subsubcategory         1899 non-null   object
 14  Subsubcategory_ID      1899 non-null   int64
dtypes: int64(12), object(3)
memory usage: 222.7+ KB
None

,Unnamed: 0,Receipt No.,Date,Time,Customer ID,Price before tax,Unit price before tax,Number,Category No.,Category name,Subcategory No.,Subcategory,Subsubcategory No.,Subsubcategory,Subsubcategory_ID
0,18,3,1,9,1616,140,140,1,21,Liquor,2113,Beer,211312,New genre,252
1,195,19,1,13,1703,100,100,1,21,Liquor,2113,Beer,211312,New genre,252
2,211,21,1,13,1519,685,685,1,21,Liquor,2118,Sake,211811,Refined sake,364
3,298,31,1,17,1620,185,185,1,21,Liquor,2116,Liquor and etc.,211612,Ice,175
4,327,33,1,12,1090,125,125,1,21,Liquor,2113,Beer,211312,New genre,252

In [3]:
top_sc = df['Subsubcategory'].value_counts()
print(top_sc.size)
print(top_sc.head())

21
Subsubcategory
New genre                                 525
Cocktail/ Cocktail of Japanese spirits    466
Beer                                      283
Ice                                       108
Refined sake                              104
Name: count, dtype: int64

In [4]:
id2sc = sorted(list(set(df['Subsubcategory'])))
sc2id = {}
for i in range(len(id2sc)):
    sc2id[id2sc[i]] = i

In [5]:
print(sc2id)

{'Alcohol-free beer': 0, 'Alcohol-free cocktails': 1, 'Beer': 2, 'Cocktail/ Cocktail of Japanese spirits': 3, 'Ice': 4, 'Imported wine': 5, 'Japanese wine': 6, 'Korui-Shochu': 7, 'Liqueur': 8, 'Low-malt beer': 9, 'Mixer': 10, 'New genre': 11, 'OthersSake': 12, 'OthersShochu': 13, 'OthersWine': 14, 'OthersWines and spirits': 15, 'Otsurui-Shochu': 16, 'Plum wine': 17, 'Refined sake': 18, 'Sparkling wine': 19, 'Whisky': 20}

In [6]:
df['Subsubcategory_ID'] = df['Subsubcategory'].map(lambda x: sc2id[x])
display(df.head())

,Unnamed: 0,Receipt No.,Date,Time,Customer ID,Price before tax,Unit price before tax,Number,Category No.,Category name,Subcategory No.,Subcategory,Subsubcategory No.,Subsubcategory,Subsubcategory_ID
0,18,3,1,9,1616,140,140,1,21,Liquor,2113,Beer,211312,New genre,11
1,195,19,1,13,1703,100,100,1,21,Liquor,2113,Beer,211312,New genre,11
2,211,21,1,13,1519,685,685,1,21,Liquor,2118,Sake,211811,Refined sake,18
3,298,31,1,17,1620,185,185,1,21,Liquor,2116,Liquor and etc.,211612,Ice,4
4,327,33,1,12,1090,125,125,1,21,Liquor,2113,Beer,211312,New genre,11

In [7]:
invoices = []
for r in df.groupby('Receipt No.'):
    s1 = set(r[1]['Subsubcategory_ID'])
    invoices.append(list(s1))
    print(list(s1))
print(len(invoices))

[11]
[11]
[18]
[4]
[11]
[2, 18]
[11, 4]
[2]
[4, 7]
[4]
[0]
[3]
[2, 11]
[11]
[14]
[2]
[0, 3]
[5]
[18, 10]
[11]
[11, 3]
[11, 2, 3]
[11, 7]
[18]
[10]
[11]
[4]
[11]
[11]
[2]
[9, 11]
[9]
[11]
[16]
[3]
[10]
[3, 11]
[2]
[4]
[0]
[11]
[11]
[11]
[2]
[11]
[3]
[4]
[11]
[11]
[11]
[3]
[0, 3, 11]
[13]
[2]
[11]
[2, 3]
[11]
[11]
[11]
[7]
[11]
[11]
[0]
[11]
[11]
[2]
[3]
[18, 11]
[9]
[3]
[11]
[3]
[2]
[2, 11]
[11]
[2]
[2, 11]
[3]
[3]
[11, 3]
[11]
[11, 3]
[2]
[11]
[11]
[1]
[9]
[7]
[4]
[3]
[3]
[11]
[2]
[2]
[11, 2, 3]
[3]
[11]
[11]
[11]
[11, 3]
[2, 18]
[2]
[2]
[11]
[11]
[3]
[11]
[11]
[3]
[5]
[10]
[2, 18]
[3]
[2, 11]
[18]
[2, 11]
[2, 3]
[2]
[11, 3]
[11, 4]
[9]
[11, 4]
[11]
[3]
[11]
[2, 11]
[6, 7]
[3]
[3, 11]
[10]
[2]
[7]
[18]
[5]
[11]
[11]
[3]
[11]
[9]
[9]
[3]
[2]
[11]
[0]
[3]
[11]
[11]
[10]
[18]
[11]
[3]
[11]
[11, 5]
[11]
[7]
[11]
[2]
[3]
[2, 11]
[3]
[2]
[0, 1, 11]
[11]
[3]
[11]
[11]
[11]
[2]
[2, 6]
[4]
[11]
[9]
[2]
[3]
[11]
[18]
[9]
[20]
[11, 4]
[2]
[0]
[11]
[2, 4]
[16, 3]
[20]
[6]
[2, 11]
[4]
[2]
[18]
[2]
[11, 3]
[11]
[10, 11]
[3]
[3]
[2]
[3]
[0]
[2]
[11]
[0, 1, 11]
[1]
[18, 11]
[3]
[3]
[20]
[2, 3]
[18]
[7]
[18]
[11, 5]
[2, 11]
[3]
[11]
[11]
[11, 2, 3]
[18]
[11]
[3]
[11]
[11]
[2]
[19]
[11]
[11, 3]
[18]
[4]
[3]
[16]
[9]
[3]
[2]
[0, 1]
[11]
[11]
[16]
[1]
[0, 11]
[7]
[11]
[10]
[2, 18]
[11, 7]
[2]
[11]
[2, 11]
[11]
[11]
[9]
[11]
[2, 11]
[2]
[3]
[4]
[7]
[11]
[4]
[0]
[4]
[11]
[5]
[13]
[4]
[2, 11]
[18]
[0]
[10]
[2]
[9, 2]
[11]
[11]
[2]
[2, 18]
[2]
[16]
[11]
[4]
[4]
[10, 11]
[11, 13]
[4]
[11]
[3]
[11]
[11]
[3]
[4]
[11]
[3]
[7]
[2]
[11]
[3]
[2, 7]
[5]
[11, 2, 3]
[11]
[3, 11]
[11]
[3]
[0, 11]
[12]
[17, 20]
[18, 11]
[19, 7]
[11]
[0]
[3]
[3]
[11, 2, 3]
[7]
[11, 3]
[11]
[9]
[11]
[11]
[2, 18]
[11]
[5]
[4, 5]
[3, 11]
[11]
[11]
[11]
[4]
[11]
[5]
[3, 11]
[7]
[3]
[11]
[3]
[11, 3]
[11]
[5]
[3]
[9]
[11, 3]
[2]
[4]
[10]
[2, 18]
[11]
[5]
[2]
[2, 11, 4]
[3]
[3]
[7]
[18, 11]
[6, 7]
[3]
[16]
[3]
[11]
[0]
[11]
[11, 2, 3]
[0]
[11]
[9]
[2]
[11]
[3]
[7]
[5]
[18]
[7]
[11]
[16]
[10]
[11]
[11]
[11]
[3, 7]
[3]
[2, 18]
[11]
[10]
[2]
[3]
[3]
[3, 4]
[11]
[18]
[18]
[11, 2, 3]
[11]
[3]
[18, 11]
[1]
[11]
[11]
[6]
[11, 2, 3]
[18]
[8]
[2, 11]
[3]
[1]
[11]
[2]
[11]
[3]
[18]
[11]
[11]
[10, 11]
[11]
[4]
[11]
[3]
[2, 4]
[3]
[3]
[11, 3]
[11]
[3]
[11]
[11]
[5]
[3]
[2]
[7]
[7]
[2, 11]
[3]
[3]
[11]
[11, 2, 3]
[2, 11]
[1]
[11]
[11]
[20]
[18]
[3]
[7]
[9, 11]
[11]
[17, 11]
[7]
[5]
[18]
[11]
[10]
[18, 11]
[3, 11]
[4]
[3]
[2, 18]
[4]
[2]
[3]
[10, 11]
[3]
[3, 2, 11]
[11, 3]
[11]
[3]
[6]
[2]
[2, 3]
[11]
[10]
[11]
[11]
[11]
[16, 9, 7]
[3]
[2]
[11]
[3]
[11]
[3]
[20]
[12]
[2, 11]
[18]
[2]
[2]
[18]
[10]
[11]
[4]
[11]
[9]
[2]
[11]
[11, 3]
[3, 4]
[4]
[11, 2, 3]
[2]
[19]
[2]
[20]
[11]
[3]
[3]
[3, 5]
[3]
[0]
[3]
[11]
[2]
[17, 2]
[16, 3]
[3]
[11]
[2, 18]
[2]
[9, 11]
[3]
[6, 7]
[2]
[3, 11]
[11]
[4]
[18]
[11]
[2]
[11]
[3]
[18]
[11, 5]
[7]
[2, 11]
[3]
[4]
[3]
[4]
[3, 4]
[4]
[11]
[11]
[7]
[11]
[3]
[3]
[0, 11, 4, 7]
[11, 5]
[11, 3]
[6]
[2, 11]
[5]
[11]
[2, 18]
[6]
[4]
[2]
[4, 7]
[0]
[2, 3]
[11, 2, 3]
[11]
[4]
[3]
[4]
[10]
[3]
[10, 2, 4]
[0, 19, 3, 16]
[16, 2]
[5]
[17]
[3]
[1]
[11, 3]
[3]
[18]
[2]
[11]
[11]
[2]
[16, 10, 2]
[4]
[3]
[2]
[2, 11]
[3]
[9, 2, 11]
[6]
[2]
[3]
[10]
[2]
[3]
[8]
[11, 4]
[4]
[7]
[18]
[4]
[9, 11]
[3]
[3]
[3]
[2, 3]
[11]
[17, 10, 18, 20]
[2]
[2, 18]
[4]
[3, 11]
[11]
[0]
[6]
[11]
[3]
[11]
[3]
[2, 4]
[6]
[11]
[11]
[18]
[11]
[2]
[3]
[11, 2, 3]
[10]
[4]
[3]
[16]
[11]
[3]
[16]
[2, 11]
[18]
[18, 4]
[9, 4]
[10]
[11]
[3]
[10]
[2]
[11]
[11, 3]
[4]
[11]
[14]
[7]
[11]
[3]
[3]
[3, 11, 6]
[1, 3]
[11]
[4]
[11]
[11]
[11]
[2]
[2, 3]
[3, 2, 11]
[11, 3]
[2]
[11]
[3]
[16, 3]
[4]
[5]
[2, 11]
[9]
[11]
[20]
[3]
[11]
[11]
[3]
[0]
[2]
[5]
[11]
[4]
[14]
[3]
[2]
[11]
[2]
[3, 11]
[3]
[10]
[3]
[3]
[11]
[11]
[4]
[3]
[3]
[11]
[11]
[18]
[11]
[2]
[18]
[3]
[11]
[0, 10, 11]
[4]
[18]
[3, 2, 11]
[9]
[2, 11]
[20]
[4]
[7]
[5]
[2, 18]
[7]
[10]
[10]
[18, 11]
[11]
[11]
[11]
[4]
[11, 15]
[4]
[4]
[3]
[7]
[3]
[18]
[2, 11]
[3]
[3]
[7]
[3]
[3]
[11, 3]
[3]
[3]
[4]
[3]
[18]
[5]
[11, 3]
[2]
[2]
[7]
[7]
[3, 11]
[10]
[2]
[18]
[2, 11]
[3]
[11]
[2]
[6, 7]
[18]
[11]
[3]
[3]
[11]
[7]
[2]
[2]
[11]
[11]
[0]
[3]
[0, 11]
[20]
[2, 3, 5]
[16]
[0]
[1, 2]
[3]
[11, 2, 3]
[0, 2, 11]
[3]
[2]
[18]
[11]
[2]
[2]
[18]
[16, 3]
[2, 3]
[9]
[3]
[11]
[7]
[20]
[2]
[4]
[2, 11]
[3, 11]
[3]
[3]
[11, 7]
[10]
[11, 3]
[9]
[18]
[11]
[2]
[11]
[11]
[18]
[2]
[10]
[16]
[11]
[5]
[9, 4]
[18]
[11]
[11, 3]
[11, 3, 4]
[11, 1, 3]
[3]
[8]
[3]
[4]
[18]
[10, 7]
[11, 3]
[3]
[3]
[3]
[3]
[0]
[6]
[4]
[11]
[2, 3]
[5]
[4]
[8, 11]
[3]
[3, 4]
[3]
[0]
[11, 3, 7]
[1]
[3, 11, 4]
[11]
[2]
[3]
[2]
[4]
[0]
[9, 5]
[3]
[18, 11]
[11]
[5]
[11]
[9, 18, 11]
[2]
[11]
[2, 18]
[11]
[11]
[10]
[1]
[2]
[5]
[11]
[4]
[9]
[10]
[10]
[3]
[2]
[3]
[2]
[11]
[3, 11]
[18, 11]
[7]
[11]
[1, 3, 20]
[2]
[11]
[11]
[9]
[9]
[4]
[3]
[1, 3]
[0]
[3]
[11]
[9, 11, 6]
[3]
[3]
[11]
[11]
[3]
[16]
[18]
[4]
[3]
[2]
[2, 18]
[7]
[18]
[11]
[4]
[14]
[11]
[16, 4]
[3]
[0]
[18]
[2]
[11, 3]
[2]
[1]
[11]
[0]
[4]
[7]
[11]
[2]
[3]
[7]
[3]
[5]
[0]
[3]
[3]
[3]
[0]
[11]
[3]
[9]
[2, 18]
[11]
[11]
[9]
[3, 11]
[3, 2, 11]
[4]
[0, 1]
[11]
[11, 3]
[18, 11]
[2]
[2]
[10, 11]
[11]
[16, 3]
[4]
[2, 18]
[5]
[10]
[2]
[11]
[3, 7]
[3]
[0]
[16]
[3]
[11, 3]
[18, 11]
[3]
[2, 6]
[0]
[18]
[18, 11]
[3]
[11]
[2]
[6]
[10, 11, 7]
[2, 11]
[3]
[5]
[2, 11]
[11]
[20]
[2]
[4]
[11, 3]
[9]
[11]
[11]
[4]
[11]
[5]
[11]
[10]
[0]
[11, 2, 3]
[2]
[2]
[0, 3]
[6, 7]
[11]
[17]
[3, 11]
[11, 3, 4]
[11]
[10]
[11]
[2]
[0]
[7]
[3]
[11]
[10, 18]
[9]
[0]
[2]
[3]
[2]
[11]
[11]
[11]
[11]
[9, 18]
[17, 3]
[3]
[9]
[10, 11, 4, 7]
[3]
[5]
[18]
[11]
[6]
[18]
[2]
[11]
[1, 11]
[9]
[0]
[11]
[11]
[2]
[11, 3]
[2, 5]
[8]
[11]
[2]
[20]
[0]
[11, 3]
[3]
[3]
[9]
[9]
[4]
[2, 18]
[11]
[11]
[11]
[2]
[11]
[4]
[3]
[4]
[2]
[3]
[2]
[11]
[11]
[9]
[18]
[2]
[16, 2, 18]
[2]
[4]
[2, 11]
[2]
[1]
[11]
[2]
[3]
[2, 5]
[3]
[11]
[11]
[10, 11]
[2, 18]
[10]
[7]
[2]
[11, 7]
[2]
[3]
[2]
[0]
[2]
[3]
[10]
[3]
[11]
[16]
[3]
[11]
[18, 11]
[0]
[11, 3]
[3]
[0]
[2]
[9]
[11]
[3]
[3, 11]
[11, 2, 3]
[3]
[10, 4]
[16, 10, 11, 4]
[5]
[3]
[2]
[11]
[11, 3]
[11]
[11]
[3]
[3]
[5]
[2]
[17, 11]
[2]
[4]
[0]
[11]
[4]
[2]
[11, 3]
[13]
[0]
[6, 7]
[11]
[3]
[2, 18]
[11, 2, 3]
[6]
[9]
[10, 11]
[6]
[11]
[18]
[11, 8, 3]
[2, 11]
[3]
[3]
[2, 11]
[3]
[3]
[18]
[13]
[3]
[3]
[3]
[2]
[4]
[18]
[3]
[2]
[2, 11]
[0]
[11]
[2]
[18]
[11]
[11]
[2]
[13]
[3]
[3]
[11]
[10, 18]
[4]
[11, 3]
[11]
[11]
[7]
[2]
[20]
[11]
[19]
[9, 4]
[5]
[20]
[3]
[2]
[3]
[3]
[2, 3]
[11]
[11]
[2, 18]
[11]
[2, 11]
[2, 11]
[3]
[2]
[0]
[11]
[0]
[4]
[11, 3]
[0, 2]
[0, 3]
[16, 11]
[11]
[0]
[3]
[2]
[18]
[11]
[18]
[2]
[18]
[18, 4]
[5]
[11]
[6, 7]
[11]
[3]
[0]
[11, 2, 3]
[11]
[11]
[11, 3]
[11]
[4]
[11]
[11]
[2]
[3]
[10]
[2]
[18]
[11]
[2]
[8]
1238

In [8]:
%time patterns = pyfpgrowth.find_frequent_patterns(invoices, 10)

CPU times: total: 0 ns
Wall time: 3.95 ms

In [9]:
%time rules = pyfpgrowth.generate_association_rules(patterns, 0.6)

CPU times: total: 0 ns
Wall time: 0 ns

In [10]:
print(rules)

{(2, 3): ((11,), 0.65625)}

In [11]:
results = []
for x in rules:
    ret = [x, rules[x][0], rules[x][1]]
    results.append(ret)
df_res = pd.DataFrame(results)
df_res.columns = ['LHS', 'RHS', 'Conf']

In [12]:
display(df_res.sort_values(by='Conf', ascending=False))

      LHS    RHS     Conf
0  (2, 3)  (11,)  0.65625

In [13]:
print(id2sc[2])
print(id2sc[3])
print(id2sc[11])

Beer
Cocktail/ Cocktail of Japanese spirits
New genre

In [14]:
n_all = len(invoices)
lift = []
for i in range(df_res.shape[0]):
    rhs = df_res.at[i, 'RHS']
    conf = df_res.at[i, 'Conf']
    n_rhs = 0
    for items in invoices:
        if set(items) >= set(rhs):
            n_rhs += 1
    lift1 = conf / (n_rhs / n_all)
    lift.append(lift1)
    
df_res['Lift'] = lift

In [15]:
display(df_res.sort_values(by='Conf', ascending=False))

      LHS    RHS     Conf      Lift
0  (2, 3)  (11,)  0.65625  1.842262

In [16]:
print( df_res.loc[ df_res['Conf'].idxmax() ])
print( df_res.loc[ df_res['Lift'].idxmax() ])

LHS       (2, 3)
RHS        (11,)
Conf     0.65625
Lift    1.842262
Name: 0, dtype: object
LHS       (2, 3)
RHS        (11,)
Conf     0.65625
Lift    1.842262
Name: 0, dtype: object