In [1]:
import numpy as np
import pandas as pd

In [2]:
csv_in = 'item.csv'
# min number of common items between target user and users in DB
min_common_users = 4
min_common_items = 4

csv_out = 'item_sim-min{}.csv'.format(min_common_users)

# To show more rows and columns
pd.options.display.max_rows = 999 
pd.options.display.max_columns = 999

In [3]:
df = pd.read_csv(csv_in, sep=',', skiprows=0, header=0)
print(df.shape)
display(df.info())
display(df.head())

(40, 15)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 40 entries, 1 to 40
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       40 non-null     int64
 1   b       40 non-null     int64
 2   c       40 non-null     int64
 3   d       40 non-null     int64
 4   e       40 non-null     int64
 5   f       40 non-null     int64
 6   g       40 non-null     int64
 7   h       40 non-null     int64
 8   i       40 non-null     int64
 9   j       40 non-null     int64
 10  k       40 non-null     int64
 11  l       40 non-null     int64
 12  m       40 non-null     int64
 13  n       40 non-null     int64
 14  o       40 non-null     int64
dtypes: int64(15)
memory usage: 5.0 KB

None

   a  b  c  d  e  f  g  h  i  j  k  l  m  n  o
1  0  0  0  0  0  3  0  0  0  0  0  0  1  0  0
2  0  1  2  0  0  0  0  4  5  0  0  0  0  3  4
3  0  0  0  0  0  0  0  0  0  0  5  0  2  0  0
4  0  0  5  0  3  0  0  0  0  1  2  0  0  1  0
5  0  3  2  0  0  5  0  0  0  0  4  0  0  0  0

In [4]:
df_corr = df.corr(min_periods=min_common_items)
display(df_corr.head())

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o
a,1.000000,-0.087020,0.090923,0.148769,-0.109320,0.014410,0.270066,-0.061008,0.068137,-0.291830,-0.169596,-0.007195,0.257753,-0.046533,-0.024873
b,-0.087020,1.000000,0.076201,0.163641,0.106096,0.086570,-0.170346,-0.052783,-0.082570,-0.147242,0.172150,0.167937,-0.167732,0.035037,0.245246
c,0.090923,0.076201,1.000000,0.036855,0.025995,0.098524,-0.069249,-0.178955,-0.133643,-0.028626,0.058401,-0.176909,-0.040014,0.069044,-0.003682
d,0.148769,0.163641,0.036855,1.000000,-0.110577,0.009412,-0.012414,-0.096118,-0.264110,-0.011342,-0.206674,0.006975,-0.108241,0.272529,-0.032531
e,-0.109320,0.106096,0.025995,-0.110577,1.000000,-0.122532,-0.103032,0.113656,-0.284647,0.216102,0.024126,0.473943,-0.190695,-0.038030,0.051949

In [5]:
df_corr.to_csv(csv_out, index=False)

In [7]:
csv_in = 'item_sim-min4.csv'
df = pd.read_csv(csv_in, sep=',', skiprows=0, header=0)

In [8]:
df.index = df.columns
print(df.shape)
print(df.info())
display(df.head())

(15, 15)
<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, a to o
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       15 non-null     float64
 1   b       15 non-null     float64
 2   c       15 non-null     float64
 3   d       15 non-null     float64
 4   e       15 non-null     float64
 5   f       15 non-null     float64
 6   g       15 non-null     float64
 7   h       15 non-null     float64
 8   i       15 non-null     float64
 9   j       15 non-null     float64
 10  k       15 non-null     float64
 11  l       15 non-null     float64
 12  m       15 non-null     float64
 13  n       15 non-null     float64
 14  o       15 non-null     float64
dtypes: float64(15)
memory usage: 2.4+ KB
None

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o
a,1.000000,-0.087020,0.090923,0.148769,-0.109320,0.014410,0.270066,-0.061008,0.068137,-0.291830,-0.169596,-0.007195,0.257753,-0.046533,-0.024873
b,-0.087020,1.000000,0.076201,0.163641,0.106096,0.086570,-0.170346,-0.052783,-0.082570,-0.147242,0.172150,0.167937,-0.167732,0.035037,0.245246
c,0.090923,0.076201,1.000000,0.036855,0.025995,0.098524,-0.069249,-0.178955,-0.133643,-0.028626,0.058401,-0.176909,-0.040014,0.069044,-0.003682
d,0.148769,0.163641,0.036855,1.000000,-0.110577,0.009412,-0.012414,-0.096118,-0.264110,-0.011342,-0.206674,0.006975,-0.108241,0.272529,-0.032531
e,-0.109320,0.106096,0.025995,-0.110577,1.000000,-0.122532,-0.103032,0.113656,-0.284647,0.216102,0.024126,0.473943,-0.190695,-0.038030,0.051949