In [1]:
import numpy as np
import pandas as pd

In [2]:
csv_in = 'df_13_assignment.csv'

min_common_users = 2
csv_out = 'df_corr-min{}.csv'.format(min_common_users)

pd.options.display.max_rows = 999 
pd.options.display.max_columns = 999

In [3]:
df = pd.read_csv(csv_in, sep=' ', skiprows=0, header=0)
print(df.shape)
display(df.info())
display(df.head())

(100, 16)
<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 1 to 100
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       100 non-null    int64
 1   b       100 non-null    int64
 2   c       100 non-null    int64
 3   d       100 non-null    int64
 4   e       100 non-null    int64
 5   f       100 non-null    int64
 6   g       100 non-null    int64
 7   h       100 non-null    int64
 8   i       100 non-null    int64
 9   j       100 non-null    int64
 10  k       100 non-null    int64
 11  l       100 non-null    int64
 12  m       100 non-null    int64
 13  n       100 non-null    int64
 14  o       100 non-null    int64
 15  p       100 non-null    int64
dtypes: int64(16)
memory usage: 13.3 KB

None

   a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p
1  0  0  0  1  0  0  0  0  4  0  1  4  0  0  5  0
2  0  0  0  0  0  2  0  0  0  0  0  0  3  0  2  0
3  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0
4  3  3  0  0  5  5  0  1  2  2  0  2  0  0  0  1
5  0  0  0  0  3  0  0  0  3  5  0  5  0  4  0  0

In [4]:
df = df.replace(0, np.nan)
display(df.head())

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p
1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,4.0,NaN,1.0,4.0,NaN,NaN,5.0,NaN
2,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,2.0,NaN
3,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,3.0,NaN,NaN,5.0,5.0,NaN,1.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,1.0
5,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,3.0,5.0,NaN,5.0,NaN,4.0,NaN,NaN

In [5]:
df_corr = df.corr(min_periods=min_common_users)
display(df_corr.head())

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p
a,1.000000,0.250365,-0.133826,-0.008552,-0.033776,-2.322865e-01,0.030647,0.275016,0.425461,0.686472,0.109152,0.168658,0.186140,0.400520,0.118609,0.408930
b,0.250365,1.000000,-0.276395,0.308607,0.259899,4.041667e-01,-0.356064,0.370349,0.010763,0.353857,0.111834,0.297670,-0.334755,-0.095223,0.408248,-0.089549
c,-0.133826,-0.276395,1.000000,-0.206725,-0.456423,1.254319e-01,-0.646756,0.239437,0.173892,-0.543557,0.553010,0.121716,-0.307171,-0.774194,-0.187500,0.394132
d,-0.008552,0.308607,-0.206725,1.000000,0.502247,-5.448876e-17,-0.428746,0.213483,-0.433013,-0.096865,-0.090289,-0.415493,-0.545922,-0.235702,-0.268135,-0.093180
e,-0.033776,0.259899,-0.456423,0.502247,1.000000,6.279309e-01,0.256186,-0.481444,-0.243204,-0.548159,0.030359,-0.119418,0.425634,0.231249,0.434524,-0.369755

In [6]:
df_corr.to_csv(csv_out, index=False)

In [7]:
csv_in = 'df_corr-min2.csv'
min_common_items = 2

pd.options.display.max_rows = 999 
pd.options.display.max_columns = 999

In [8]:
df_corr

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p
a,1.000000,0.250365,-0.133826,-8.551695e-03,-0.033776,-2.322865e-01,0.030647,0.275016,0.425461,6.864721e-01,0.109152,0.168658,0.186140,0.400520,0.118609,4.089304e-01
b,0.250365,1.000000,-0.276395,3.086067e-01,0.259899,4.041667e-01,-0.356064,0.370349,0.010763,3.538569e-01,0.111834,0.297670,-0.334755,-0.095223,0.408248,-8.954909e-02
c,-0.133826,-0.276395,1.000000,-2.067246e-01,-0.456423,1.254319e-01,-0.646756,0.239437,0.173892,-5.435573e-01,0.553010,0.121716,-0.307171,-0.774194,-0.187500,3.941317e-01
d,-0.008552,0.308607,-0.206725,1.000000e+00,0.502247,-5.448876e-17,-0.428746,0.213483,-0.433013,-9.686462e-02,-0.090289,-0.415493,-0.545922,-0.235702,-0.268135,-9.318020e-02
e,-0.033776,0.259899,-0.456423,5.022472e-01,1.000000,6.279309e-01,0.256186,-0.481444,-0.243204,-5.481590e-01,0.030359,-0.119418,0.425634,0.231249,0.434524,-3.697550e-01
f,-0.232286,0.404167,0.125432,-5.448876e-17,0.627931,1.000000e+00,0.179379,-0.075032,0.213922,-4.010236e-01,0.326731,0.047782,-0.471375,-0.240099,-0.196344,-7.475581e-01
g,0.030647,-0.356064,-0.646756,-4.287465e-01,0.256186,1.793794e-01,1.000000,-0.484544,0.133545,1.463014e-01,0.391555,-0.365858,-0.079950,0.557370,0.452267,-5.116817e-01
h,0.275016,0.370349,0.239437,2.134831e-01,-0.481444,-7.503225e-02,-0.484544,1.000000,0.664204,3.855146e-01,-0.308327,-0.294134,-0.355784,-0.075378,-0.041667,6.101702e-01
i,0.425461,0.010763,0.173892,-4.330127e-01,-0.243204,2.139224e-01,0.133545,0.664204,1.000000,-2.746175e-02,-0.664933,0.306295,-0.362738,0.367313,-0.100728,-1.767767e-01
j,0.686472,0.353857,-0.543557,-9.686462e-02,-0.548159,-4.010236e-01,0.146301,0.385515,-0.027462,1.000000e+00,0.873038,0.615457,-0.206607,0.508001,0.662266,7.690649e-17
k,0.109152,0.111834,0.553010,-9.028939e-02,0.030359,3.267307e-01,0.391555,-0.308327,-0.664933,8.730379e-01,1.000000,-0.107486,-0.090536,-0.102433,0.418364,4.178145e-01
l,0.168658,0.297670,0.121716,-4.154934e-01,-0.119418,4.778185e-02,-0.365858,-0.294134,0.306295,6.154575e-01,-0.107486,1.000000,-0.238366,-0.237023,-0.468545,7.366351e-01
m,0.186140,-0.334755,-0.307171,-5.459220e-01,0.425634,-4.713754e-01,-0.079950,-0.355784,-0.362738,-2.066069e-01,-0.090536,-0.238366,1.000000,0.216386,0.140964,2.424891e-01
n,0.400520,-0.095223,-0.774194,-2.357023e-01,0.231249,-2.400994e-01,0.557370,-0.075378,0.367313,5.080005e-01,-0.102433,-0.237023,0.216386,1.000000,0.085706,-2.477168e-01
o,0.118609,0.408248,-0.187500,-2.681355e-01,0.434524,-1.963442e-01,0.452267,-0.041667,-0.100728,6.622662e-01,0.418364,-0.468545,0.140964,0.085706,1.000000,-4.222883e-01
p,0.408930,-0.089549,0.394132,-9.318020e-02,-0.369755,-7.475581e-01,-0.511682,0.610170,-0.176777,7.690649e-17,0.417815,0.736635,0.242489,-0.247717,-0.422288,1.000000e+00

In [9]:
df = pd.read_csv(csv_in, sep=',', skiprows=0, header=0)
df.index = df.columns
print(df.shape)
print(df.info())
display(df.head())

(16, 16)
<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, a to p
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       16 non-null     float64
 1   b       16 non-null     float64
 2   c       16 non-null     float64
 3   d       16 non-null     float64
 4   e       16 non-null     float64
 5   f       16 non-null     float64
 6   g       16 non-null     float64
 7   h       16 non-null     float64
 8   i       16 non-null     float64
 9   j       16 non-null     float64
 10  k       16 non-null     float64
 11  l       16 non-null     float64
 12  m       16 non-null     float64
 13  n       16 non-null     float64
 14  o       16 non-null     float64
 15  p       16 non-null     float64
dtypes: float64(16)
memory usage: 2.7+ KB
None

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p
a,1.000000,0.250365,-0.133826,-0.008552,-0.033776,-2.322865e-01,0.030647,0.275016,0.425461,0.686472,0.109152,0.168658,0.186140,0.400520,0.118609,0.408930
b,0.250365,1.000000,-0.276395,0.308607,0.259899,4.041667e-01,-0.356064,0.370349,0.010763,0.353857,0.111834,0.297670,-0.334755,-0.095223,0.408248,-0.089549
c,-0.133826,-0.276395,1.000000,-0.206725,-0.456423,1.254319e-01,-0.646756,0.239437,0.173892,-0.543557,0.553010,0.121716,-0.307171,-0.774194,-0.187500,0.394132
d,-0.008552,0.308607,-0.206725,1.000000,0.502247,-5.448876e-17,-0.428746,0.213483,-0.433013,-0.096865,-0.090289,-0.415493,-0.545922,-0.235702,-0.268135,-0.093180
e,-0.033776,0.259899,-0.456423,0.502247,1.000000,6.279309e-01,0.256186,-0.481444,-0.243204,-0.548159,0.030359,-0.119418,0.425634,0.231249,0.434524,-0.369755

In [10]:
def predict_scores(df_sim, ser_target):
    ret = {}
    for item1 in df_sim.index:
        v1 = df_sim.loc[item1]
        if v1.notnull().sum() < min_common_items: continue
        v11 = v1[ v1.notnull() ]
        t11 = ser_target[ v1.notnull() ]
        pred1 = (v11 * t11).sum() / np.abs(v11).sum()
        ret[item1] = pred1
    
    ser_ret = pd.Series(ret)
    
    return ser_ret.sort_values(ascending=False)

In [11]:
df

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p
a,1.000000,0.250365,-0.133826,-8.551695e-03,-0.033776,-2.322865e-01,0.030647,0.275016,0.425461,6.864721e-01,0.109152,0.168658,0.186140,0.400520,0.118609,4.089304e-01
b,0.250365,1.000000,-0.276395,3.086067e-01,0.259899,4.041667e-01,-0.356064,0.370349,0.010763,3.538569e-01,0.111834,0.297670,-0.334755,-0.095223,0.408248,-8.954909e-02
c,-0.133826,-0.276395,1.000000,-2.067246e-01,-0.456423,1.254319e-01,-0.646756,0.239437,0.173892,-5.435573e-01,0.553010,0.121716,-0.307171,-0.774194,-0.187500,3.941317e-01
d,-0.008552,0.308607,-0.206725,1.000000e+00,0.502247,-5.448876e-17,-0.428746,0.213483,-0.433013,-9.686462e-02,-0.090289,-0.415493,-0.545922,-0.235702,-0.268135,-9.318020e-02
e,-0.033776,0.259899,-0.456423,5.022472e-01,1.000000,6.279309e-01,0.256186,-0.481444,-0.243204,-5.481590e-01,0.030359,-0.119418,0.425634,0.231249,0.434524,-3.697550e-01
f,-0.232286,0.404167,0.125432,-5.448876e-17,0.627931,1.000000e+00,0.179379,-0.075032,0.213922,-4.010236e-01,0.326731,0.047782,-0.471375,-0.240099,-0.196344,-7.475581e-01
g,0.030647,-0.356064,-0.646756,-4.287465e-01,0.256186,1.793794e-01,1.000000,-0.484544,0.133545,1.463014e-01,0.391555,-0.365858,-0.079950,0.557370,0.452267,-5.116817e-01
h,0.275016,0.370349,0.239437,2.134831e-01,-0.481444,-7.503225e-02,-0.484544,1.000000,0.664204,3.855146e-01,-0.308327,-0.294134,-0.355784,-0.075378,-0.041667,6.101702e-01
i,0.425461,0.010763,0.173892,-4.330127e-01,-0.243204,2.139224e-01,0.133545,0.664204,1.000000,-2.746175e-02,-0.664933,0.306295,-0.362738,0.367313,-0.100728,-1.767767e-01
j,0.686472,0.353857,-0.543557,-9.686462e-02,-0.548159,-4.010236e-01,0.146301,0.385515,-0.027462,1.000000e+00,0.873038,0.615457,-0.206607,0.508001,0.662266,7.690649e-17
k,0.109152,0.111834,0.553010,-9.028939e-02,0.030359,3.267307e-01,0.391555,-0.308327,-0.664933,8.730379e-01,1.000000,-0.107486,-0.090536,-0.102433,0.418364,4.178145e-01
l,0.168658,0.297670,0.121716,-4.154934e-01,-0.119418,4.778185e-02,-0.365858,-0.294134,0.306295,6.154575e-01,-0.107486,1.000000,-0.238366,-0.237023,-0.468545,7.366351e-01
m,0.186140,-0.334755,-0.307171,-5.459220e-01,0.425634,-4.713754e-01,-0.079950,-0.355784,-0.362738,-2.066069e-01,-0.090536,-0.238366,1.000000,0.216386,0.140964,2.424891e-01
n,0.400520,-0.095223,-0.774194,-2.357023e-01,0.231249,-2.400994e-01,0.557370,-0.075378,0.367313,5.080005e-01,-0.102433,-0.237023,0.216386,1.000000,0.085706,-2.477168e-01
o,0.118609,0.408248,-0.187500,-2.681355e-01,0.434524,-1.963442e-01,0.452267,-0.041667,-0.100728,6.622662e-01,0.418364,-0.468545,0.140964,0.085706,1.000000,-4.222883e-01
p,0.408930,-0.089549,0.394132,-9.318020e-02,-0.369755,-7.475581e-01,-0.511682,0.610170,-0.176777,7.690649e-17,0.417815,0.736635,0.242489,-0.247717,-0.422288,1.000000e+00

In [12]:
def get_recomm_by_item_sim(df, target_dic):
    ser_target = pd.Series(target_dic)
    df_scores = df[ ser_target.index ]
    df_scores = df_scores.drop(index=ser_target.index)
    recomm = predict_scores(df_scores, ser_target)
    
    return recomm

In [13]:
recomm = get_recomm_by_item_sim(df,
                                {'a':2, 'b':3, 'c':1,
                                 'e':4, 'k':3})
print('Number of items calculated:', len(recomm))
print('Recommendation:')
print(recomm.head())

Number of items calculated: 11
Recommendation:
o    2.723027
f    2.543056
d    2.185659
j    0.771172
l    0.677238
dtype: float64